//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingTree
    {
        public AccountingTree()
        {
            this.AccountingTree1 = new HashSet<AccountingTree>();
            this.FinancialTransactions = new HashSet<FinancialTransaction>();
            this.FinancialTransactions1 = new HashSet<FinancialTransaction>();
            this.Projects = new HashSet<Project>();
            this.ProjectUnits = new HashSet<ProjectUnit>();
            this.Suppliers = new HashSet<Supplier>();
        }
    
        public int Id { get; set; }
        public string NodeName { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<bool> IsPayment { get; set; }
        public Nullable<bool> IsReceivable { get; set; }
        public Nullable<double> CurrentBalance { get; set; }
        public Nullable<int> KeyAccountID { get; set; }
        public string AccountingCode { get; set; }
    
        public virtual ICollection<AccountingTree> AccountingTree1 { get; set; }
        public virtual AccountingTree AccountingTree2 { get; set; }
        public virtual ICollection<FinancialTransaction> FinancialTransactions { get; set; }
        public virtual ICollection<FinancialTransaction> FinancialTransactions1 { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<ProjectUnit> ProjectUnits { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
    }
}
