//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public Contract()
        {
            this.ContractOwners = new HashSet<ContractOwner>();
            this.Installments = new HashSet<Installment>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Paid { get; set; }
        public Nullable<double> Remaining { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<ContractOwner> ContractOwners { get; set; }
        public virtual Project Project { get; set; }
        public virtual ProjectUnit ProjectUnit { get; set; }
        public virtual ICollection<Installment> Installments { get; set; }
    }
}
