//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string SSN { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public Nullable<System.DateTime> HiringDate { get; set; }
        public Nullable<int> BasicSalary { get; set; }
        public Nullable<int> SalaryType { get; set; }
        public string Title { get; set; }
        public Nullable<int> EmpAccID { get; set; }
        public Nullable<int> ImprestAccID { get; set; }
        public Nullable<int> BenifitAccID { get; set; }
        public Nullable<int> PenaltyAccID { get; set; }
    }
}
