//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeImprest
    {
        public int Id { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<double> Imprest { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
