//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installment
    {
        public int Id { get; set; }
        public Nullable<int> ContractID { get; set; }
        public Nullable<int> ResponsibleID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<double> Amount { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
