//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.SupplierInvoiceLines = new HashSet<SupplierInvoiceLine>();
        }
    
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> PurchaseUnit { get; set; }
        public Nullable<int> SalesUnit { get; set; }
        public Nullable<int> PtoSRate { get; set; }
        public Nullable<int> AccountID { get; set; }
    
        public virtual AccountingTree AccountingTree { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ICollection<SupplierInvoiceLine> SupplierInvoiceLines { get; set; }
    }
}
