//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectUnit
    {
        public int Id { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<double> UnitSpace { get; set; }
        public Nullable<int> UnitType { get; set; }
        public Nullable<int> FloorNumber { get; set; }
        public Nullable<double> ExpectedPrice { get; set; }
        public Nullable<int> Finishing { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<int> AccountingID { get; set; }
    
        public virtual AccountingTree AccountingTree { get; set; }
    }
}
