//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screen
    {
        public Screen()
        {
            this.UserAccesses = new HashSet<UserAccess>();
        }
    
        public int ID { get; set; }
        public string ScreenURL { get; set; }
        public string Title { get; set; }
        public byte[] GroupName { get; set; }
    
        public virtual ICollection<UserAccess> UserAccesses { get; set; }
    }
}
