//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public Stock()
        {
            this.StockTransactions = new HashSet<StockTransaction>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<double> Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<StockTransaction> StockTransactions { get; set; }
    }
}
