//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierInvoice
    {
        public SupplierInvoice()
        {
            this.SupplierInvoiceLines = new HashSet<SupplierInvoiceLine>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string SupplierReferenaceNo { get; set; }
        public Nullable<int> InvoiceAccount { get; set; }
        public Nullable<double> InvoiceTotal { get; set; }
        public Nullable<double> InvoiceDiscount { get; set; }
        public Nullable<double> InvoiceNet { get; set; }
        public Nullable<bool> Departed { get; set; }
        public Nullable<int> LastEditBy { get; set; }
        public Nullable<int> ProjectID { get; set; }
    
        public virtual AccountingTree AccountingTree { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<SupplierInvoiceLine> SupplierInvoiceLines { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
    }
}
