//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccess
    {
        public int UserID { get; set; }
        public int ScreenID { get; set; }
        public Nullable<bool> CanEdit { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public Nullable<bool> Opt1 { get; set; }
        public int Id { get; set; }
    
        public virtual Screen Screen { get; set; }
        public virtual User User { get; set; }
    }
}
