//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CustomerInvoices = new HashSet<CustomerInvoice>();
            this.FinancialTransactions = new HashSet<FinancialTransaction>();
            this.SupplierInvoices = new HashSet<SupplierInvoice>();
            this.UserAccesses = new HashSet<UserAccess>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<CustomerInvoice> CustomerInvoices { get; set; }
        public virtual ICollection<FinancialTransaction> FinancialTransactions { get; set; }
        public virtual ICollection<SupplierInvoice> SupplierInvoices { get; set; }
        public virtual ICollection<UserAccess> UserAccesses { get; set; }
    }
}
